##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.metricbeat:7.1.1 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/git-repository/*
COPY ./ /conteco/git-repository/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/usr/local/bin/docker-entrypoint"
# COPY ./conteco/metricbeat/base/usr/share/metricbeat/metricbeat.yml /usr/share/metricbeat/metricbeat.yml
#USER metricbeat
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="metricbeat" \
    CONTECO_NAME="base" \
    CONTECO_TAG="7.1.1" \
    CONTECO_BASE="external.metricbeat:7.1.1" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="metricbeat" \
      io.vcweb.name="base" \
      io.vcweb.tag="7.1.1" \
      io.vcweb.base="external.metricbeat:7.1.1" \
      io.vcweb.build="image-base" \
      io.vcweb.label="Conteco metricbeat base" \
      io.vcweb.description="The ElasticSearch Metricbeat base image." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.metricbeat.base --help" 
##### END image.base/Dockerfile/env-labels-footer #####
