#!/usr/bin/env bash

export CONTECO_LABEL="metricbeat.base - ConteEco"
export CONTECO_DESCRIPTION="The ElasticSearch Metricbeat base image."

export CONTECO_TYPE="metricbeat"
export CONTECO_NAME="base"
export CONTECO_TAG="7.9.2"

export CONTECO_BASE="external.metricbeat:7.9.2"
export CONTECO_BUILD="image-base"
