#!/usr/bin/env bash

export CONTECO_LABEL="Conteco metricbeat base"
export CONTECO_DESCRIPTION="The ElasticSearch Metricbeat base image."

export CONTECO_TYPE="metricbeat"
export CONTECO_NAME="base"
export CONTECO_TAG="6.6.2"

export CONTECO_BASE="external.metricbeat:6.6.2"
export CONTECO_BUILD="image-base"
